#!/bin/bash -l
#SBATCH --job-name=0.85DH
#SBATCH --time=72:00:00
#SBATCH --partition=lrgmem
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=48

module load intel/2020

~/Software/Mine/vibronics/tools/seed/seed.exe -w wfn-2.in -v vibration1.in vibration2.in vibration3.in vibration4.in -i initial-freq-1.in initial-freq-2.in -f final-freq-1.in final-freq-2.in final-freq-3.in final-freq-4.in -t transformation-matrix.in -s shift-vector.in -d 0.034856 0.652287 0  > seed.log

~/Software/Mine/vibronics/v1/vibronics.exe -w wfn-2.in -v vibration1.in vibration2.in vibration3.in vibration4.in -H Hd_1-1.in Hd_1-2.in Hd_1-3.in Hd_2-2.in Hd_2-3.in Hd_3-3.in -f final-freq-1.in final-freq-2.in final-freq-3.in final-freq-4.in -p seed -m 10000 > Lanczos.log

~/Software/Mine/vibronics/tools/eig/eig.exe -a alpha.txt -b beta.txt > eig.log
