#!/bin/bash -l
#SBATCH --job-name=asym
#SBATCH --time=72:00:00
#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4

export OMP_NUM_THREADS=4

~/Software/Mine/diabatz/tools/vibration/v1/vibration.exe -f default -i opt.IntCoordDef -t 1 -x asym.xyz -m mass.txt -d default IntCoordDef SAS.in pretrain-Hd.in pretrain-Hd.net pretrain-11.in pretrain-12.in pretrain-13.in pretrain-14.in pretrain-22.in pretrain-23.in pretrain-24.in pretrain-33.in pretrain-34.in pretrain-44.in default IntCoordDef SAS.in Hd.in Hd.net 11.in 12.in 13.in 14.in 22.in 23.in 24.in 33.in 34.in 44.in -o min.log -a
