#!/bin/bash -l
#SBATCH --account=dyarkon1
#SBATCH --job-name=bound
#SBATCH --time=72:00:00
#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4

export OMP_NUM_THREADS=4

~/Software/Mine/diabatz/v1.3.0/diabatz.exe --pretrained default IntCoordDef SAS.in pretrain/C2v_Hd.in pretrain/C2v_Hd.net pretrain/C2v_11.in pretrain/C2v_12.in pretrain/C2v_13.in pretrain/C2v_14.in pretrain/C2v_22.in pretrain/C2v_23.in pretrain/C2v_24.in pretrain/C2v_33.in pretrain/C2v_34.in pretrain/C2v_44.in -f default -i IntCoordDef -s SAS.in -n Hd.in -l 11.in 12.in 13.in 14.in 22.in 23.in 24.in 33.in 34.in 44.in -d data/critical/min-A1/ data/critical/sad-A1/ data/critical/min-B1/ data/critical/min-B2/ data/critical/sad-B2/ data/critical/min-A2/ data/linear-path/min-B1_min-B2/ data/other/benzene/list.txt data/other/in-benzene/list.txt data/other/out-of-benzene/list.txt data/other/NH2-angles/list.txt -z -286.1075216397 -r regularization/reg -p regularization/prior -m 20 > diabatz.log
