#!/bin/bash -l
#SBATCH --job-name=log2-4
#SBATCH --time=48:00:00
#SBATCH --qos=regular
#SBATCH --constraint=haswell
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=32
#SBATCH --cpus-per-task=2

cd 1_C2v_2nd-order
~/Software/Mine/diabatz/v0/diabatz.exe -f default -i IntCoordDef -s SAS.in -n Hd.in -l 11.in 12.in 13.in 14.in 22.in 23.in 24.in 33.in 34.in 44.in -d C2v_list.txt -z -286.1075216397 --energy_weight 0.015 --gradient_weight 0.02 -g 0.013003140199998597 0.1622015817999909 0.19160296519999065 0.24159386550002182 > log
cd ..

cp 1_C2v_2nd-order/Hd.net 2_bound_2nd-order
cd 2_bound_2nd-order
~/Software/Mine/diabatz/v0/diabatz.exe -f default -i IntCoordDef -s SAS.in -n Hd.in -l 11.in 12.in 13.in 14.in 22.in 23.in 24.in 33.in 34.in 44.in -d bound_list.txt -z -286.1075216397 --energy_weight 0.015 --gradient_weight 0.02 -c Hd.net > log
cd ..

cp 2_bound_2nd-order/Hd.net 3_1.1_2nd-order
cd 3_1.1_2nd-order
~/Software/Mine/diabatz/v0/diabatz.exe -f default -i IntCoordDef -s SAS.in -n Hd.in -l 11.in 12.in 13.in 14.in 22.in 23.in 24.in 33.in 34.in 44.in -d 1.1_list.txt -z -286.1075216397 --energy_weight 0.015 --gradient_weight 0.02 -c Hd.net > log
cd ..

cp 3_1.1_2nd-order/Hd.net 4_1.2_2nd-order
cd 4_1.2_2nd-order
~/Software/Mine/diabatz/v0/diabatz.exe -f default -i IntCoordDef -s SAS.in -n Hd.in -l 11.in 12.in 13.in 14.in 22.in 23.in 24.in 33.in 34.in 44.in -d 1.2_list.txt -z -286.1075216397 --energy_weight 0.015 --gradient_weight 0.02 -c Hd.net > log
cd ..
